WIP: AdobeSign cloud functions
yeatmanlab/roar-firekit pull request #128
Opened 2024-07-06 00:18 UTC by Emily-ejag

- **adding createAdobeSignAgreement function**
- **adding adobeSign cloud functions**

## Proposed changes

## Types of changes

What types of changes does this pull request introduce?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (non-breaking change that does not add functionality but makes code cleaner or more efficient)
- [ ] Documentation Update
- [ ] Tests (new or updated tests)
- [ ] Style (changes to code styling)
- [ ] CI (continuous integration changes)
- [ ] Repository Maintenance
- [ ] Other (please describe below)

## Checklist

- [ ] I have read the [guidelines for contributing](https://github.com/yeatmanlab/roar-dashboard/blob/main/.github/CONTRIBUTING.md).
- [ ] The changes in this PR are as small as they can be. They represent one and only one fix or enhancement.
- [ ] Linting checks pass with my changes.
- [ ] Any existing unit tests pass with my changes.
- [ ] Any existing end-to-end tests pass with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] If this PR fixes an existing issue, I have added a unit or end-to-end test that will detect if this issue reoccurs.
- [ ] I have added JSDoc comments as appropriate.
- [ ] I have added the necessary documentation to the [roar-docs repository](https://github.com/yeatmanlab/roar-docs).
- [ ] I have shared this PR on the roar-pr-reviews channel (if I have access)
- [ ] I have linked relevant issues (if any)

## Justification of missing checklist items

## Further comments

2024-07-07 11:47 UTC, richford requested changes
Looks good. Just very minor camelCase changes requested.

2024-07-07 11:47 UTC, richford commented on src/firekit.ts
> +      const result = await cloudgetAdobeSignAgreementStatus({
```suggestion
      const result = await cloudGetAdobeSignAgreementStatus({
```

2024-07-07 11:47 UTC, richford commented on src/firekit.ts
> +    const cloudgetAdobeSignAgreementStatus = httpsCallable(this.admin!.functions, 'getAdobeSignAgreementStatus');
```suggestion
    const cloudGetAdobeSignAgreementStatus = httpsCallable(this.admin!.functions, 'getAdobeSignAgreementStatus');
```

2024-07-07 11:47 UTC, richford commented on src/firekit.ts
> +      const result = await cloudgetAdobeSignSigningUrl({
```suggestion
      const result = await cloudGetAdobeSignSigningUrl({
```

2024-07-07 11:47 UTC, richford commented on src/firekit.ts
> +    const cloudgetAdobeSignSigningUrl = httpsCallable(this.admin!.functions, 'getAdobeSignSigningUrl');
```suggestion
    const cloudGetAdobeSignSigningUrl = httpsCallable(this.admin!.functions, 'getAdobeSignSigningUrl');
```

2024-07-08 16:08 UTC, Emily-ejag commented on src/firekit.ts
> +      const result = await cloudgetAdobeSignAgreementStatus({
done!

2024-07-18 21:54 UTC, richford requested changes
These all look good but can I please request tsdoc docstrings for these new methods. See https://github.com/yeatmanlab/roar-firekit/blob/f8929f95324f97288a6f5f0c98af0db991726af2/src/firekit.ts#L631 for an example.

2024-07-18 22:02 UTC, Emily-ejag commented
> These all look good but can I please request tsdoc docstrings for these new methods. See
> 
> https://github.com/yeatmanlab/roar-firekit/blob/f8929f95324f97288a6f5f0c98af0db991726af2/src/firekit.ts#L631
> 
> for an example.

Done!

2024-07-18 23:21 UTC, richford approved these changes

2024-07-18 23:21 UTC, merged