CU-8689wekxm App Check Throttling Error
yeatmanlab/roar-firekit pull request #152
Opened 2024-09-24 21:53 UTC by ksmontville

## Proposed changes

## Types of changes

What types of changes does this pull request introduce?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (non-breaking change that does not add functionality but makes code cleaner or more efficient)
- [ ] Documentation Update
- [ ] Tests (new or updated tests)
- [ ] Style (changes to code styling)
- [ ] CI (continuous integration changes)
- [ ] Repository Maintenance
- [ ] Other (please describe below)

## Checklist

- [ ] I have read the [guidelines for contributing](https://github.com/yeatmanlab/roar-dashboard/blob/main/.github/CONTRIBUTING.md).
- [ ] The changes in this PR are as small as they can be. They represent one and only one fix or enhancement.
- [ ] Linting checks pass with my changes.
- [ ] Any existing unit tests pass with my changes.
- [ ] Any existing end-to-end tests pass with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] If this PR fixes an existing issue, I have added a unit or end-to-end test that will detect if this issue reoccurs.
- [ ] I have added JSDoc comments as appropriate.
- [ ] I have added the necessary documentation to the [roar-docs repository](https://github.com/yeatmanlab/roar-docs).
- [ ] I have shared this PR on the roar-pr-reviews channel (if I have access)
- [ ] I have linked relevant issues (if any)

## Justification of missing checklist items

## Further comments

2024-09-24 21:53 UTC, richford commented
Task linked: [CU-8689wekxm Investigate App Check Throttling Error](https://app.clickup.com/t/8689wekxm)

2024-09-24 22:09 UTC, maximilianoertel requested changes
I have not dug deep into the subject, so please correct me if I'm missing something!

However, given this explanation of [how the AppCheck throttling works](https://github.com/firebase/firebase-js-sdk/issues/7371#issuecomment-1603069415) (or better what causes the throttling to kick in), the approach taken here seems to be a little problematic. 

The `catch` block will log the errors and prevent an error from being thrown, but the dashboard's XHR requests to Firebase will still fail as soon as we enable AppCheck enforcement. As far as I remember, there is nothing in place that will gracefully handle these errors on the dashboard. 

I know, at this point AppCheck is only running in monitoring, but the goal should of course be to enable actual enforcement. So if this PR is intended to just temporarily resolve the issue, it would be good to add some inline `@TODO` or `@NOTE` on line 208 that explains that this is only a temporary workaround which will break the application once enforcement mode is activated. 

Otherwise, we should have the `firekit` throw dedicated errors which we can catch during initialisation on the dashboard, and based on that then display meaningful errors to the users in the form of a redirect to an error page (and, logging to Sentry).

What do you think?

2024-09-25 16:18 UTC, Emily-ejag commented
> I have not dug deep into the subject, so please correct me if I'm missing something!
> 
> However, given this explanation of [how the AppCheck throttling works](https://github.com/firebase/firebase-js-sdk/issues/7371#issuecomment-1603069415) (or better what causes the throttling to kick in), the approach taken here seems to be a little problematic.
> 
> The `catch` block will log the errors and prevent an error from being thrown, but the dashboard's XHR requests to Firebase will still fail as soon as we enable AppCheck enforcement. As far as I remember, there is nothing in place that will gracefully handle these errors on the dashboard.
> 
> I know, at this point AppCheck is only running in monitoring, but the goal should of course be to enable actual enforcement. So if this PR is intended to just temporarily resolve the issue, it would be good to add some inline `@TODO` or `@NOTE` on line 208 that explains that this is only a temporary workaround which will break the application once enforcement mode is activated.
> 
> Otherwise, we should have the `firekit` throw dedicated errors which we can catch during initialisation on the dashboard, and based on that then display meaningful errors to the users in the form of a redirect to an error page (and, logging to Sentry).
> 
> What do you think?

I think this is good feeback. When that time comes, we can throw dedicated errors during initialization and display meaningful messages to users, potentially with a redirect to an error page. But for now, like you said we can ad a `TODO` or a `NOTE` @ksmontville what do you think?

2024-09-25 20:41 UTC, Emily-ejag approved these changes

2024-10-10 21:04 UTC, closed without merging